KMKoushik/squeeth-portal

- container/Auction/LiveAuction.tsx
- container/SqueethInfo.tsx
- pages/auction.tsx
- styles/globals.css
- theme.ts
Added some typography for the heading and numbers.
> Add new fonts

- hooks/useCrab.ts
Reverts KMKoushik/squeeth-portal#14
> Revert "new multiplier"

- container/CrabV2/Auction/AuctionBody.tsx
https://user-images.githubusercontent.com/29926727/180283455-c2b7bc21-1f42-4645-aaa0-c8855149b965.mov
> Add Balance Field and Set to Max On-Click

- pages/api/auction/getUserBids.ts
- server/utils/firebase-admin.ts
**What type of PR is this?**
- new feature
**What this PR does / why we need it?**:
-Enables user fetch bids for current auction
**Note**:
Only bids for current auction can be fetched.
> fetch user bids endpoint added

- container/CrabV2/Auction/Admin/AdminBidView.tsx
- container/CrabV2/Auction/Auction.tsx
- container/CrabV2/Auction/AuctionBody.tsx
- container/CrabV2/Auction/Bids.tsx
- hooks/init/useInitAuction.ts
- pages/api/auction/getLatestAuction.ts
- store/crabV2Store.ts
- utils/auction.ts
- utils/math.ts
What type of PR is this?
- feature update
What this PR does / why we need it?:
- Adds green, and red backgrounds to bids
- Warn's user if the quote price is worse than the est. clearing price
- Update correct status for API users
> Add colors to bids, warning for clearing price

- container/CrabV2/Auction/Auction.tsx
- container/CrabV2/Auction/AuctionBody.tsx
- container/CrabV2/Auction/Bids.tsx
- utils/auction.ts
What does this PR do?
- on settlement screen under “filled” show “yes” or “partial - amt” eg. “partial - 235”  
- when regan was submitting bid everytime she deleted the 0 in the input on the modal, she got client side error & user ES could not submit a bid
- have the date in the "Auction" title eg. instead of saying "Auction" it says "08/10/22 Auction" or sth
> Add bids priority fixes

- container/CrabV2/Auction/Admin/CreateAuction.tsx
4 digit Number raised to the 18 power emits scientific notation
> Fix: Number raised to the 18 power emits scientific notation

- .eslintrc.json
- container/CrabV2/Auction/Admin/AdminBidView.tsx
- container/CrabV2/Auction/Admin/AuctionDetails.tsx
- container/CrabV2/Auction/Approvals.tsx
- container/CrabV2/Auction/Auction.tsx
- hooks/init/useInitAccount.ts
- pages/_app.tsx
- pages/api/auction/createOrEditBid.ts
- store/crabV2Store.ts
- types/index.ts
- utils/math.ts
- Approval not showing if non zero amount is approved
- manager view estimated oSQTH and ETH set to 0 when auction starts or when size set 
- manager view doesn’t have DVOL, would be nice
> Fix approval and admin issue

- container/CrabV2/Auction/Approvals.tsx
- container/CrabV2/Auction/Auction.tsx
- container/CrabV2/Auction/AuctionHistory.tsx
- pages/auction.tsx
- pages/auctionHistory/[id].tsx
- pages/auctionHistory/index.tsx
- styles/Auction.module.css
This is a temporary design which will be responsive and usable to a extent. I will create another PR to make the UI more mobile friendly as discussed.
> Add - Basic Responsive Design

- container/CrabV2/Auction/Auction.tsx
- container/CrabV2/Auction/AuctionBody.tsx
- container/CrabV2/Auction/AuctionInfo.tsx
- container/CrabV2/Auction/Bids.tsx
- pages/_middleware.ts
- tests/unit/auction.test.ts
- utils/auction.ts
Fixes ENG-561
Fixes ENG-555
Fixes ENG-533
Fixes ENG-562
Fixes ENG-572
Fixes ENG-567
Fixes ENG-566
> Switch price and qty input

- container/CrabV2/Auction/Admin/AdminBidView.tsx
- container/CrabV2/Auction/Approvals.tsx
- container/CrabV2/Auction/Auction.tsx
- container/CrabV2/Auction/AuctionBody.tsx
- container/CrabV2/Auction/AuctionInfo.tsx
- container/CrabV2/Auction/Bids.tsx
- pages/_middleware.ts
- tests/unit/auction.test.ts
- types/index.ts
- utils/auction.ts
Fixes ENG-561
Fixes ENG-555
Fixes ENG-533
Fixes ENG-562
Fixes ENG-572
Fixes ENG-567
Fixes ENG-566
Fixes ENG-585
Fixes ENG-584
Fixes ENG-583
> September Release 1

- container/CrabV2/Auction/Approvals.tsx
> Fix approval amount

- server/utils/telegram-bot.ts
> tg bot text change ENG-702

- pages/_middleware.ts
- pages/api/auction/getLastHedge.ts
**Details**
1. Added endpoint to fetch the last closed hedge auction.
> Add last hedge endpoint

- container/CrabV2/Auction/Admin/AuctionDetails.tsx
- container/CrabV2/Auction/Auction.tsx
- hooks/useAuctionEstimate.ts
- hooks/useBullAuction.ts
- pages/auction.tsx
- utils/auction.ts
> Show estimates based on auction type

- container/CrabV2/Auction/Admin/CreateAuction.tsx
Fixes ENG-1352
Fixes ENG-1381
Fixes ENG-1382
> Fix auction admin bugs

- container/CrabV2/Auction/AuctionBody.tsx
> Fix: Don't reset inputs on new bids

- abis/bullNetting.json
- constants/address.ts
- constants/contracts.ts
- container/CalmBull/Netting/BullNetting.tsx
- container/CrabV2/Netting/NettingAdmin.tsx
- hooks/init/useInitBull.ts
- hooks/init/useInitBullNetting.ts
- pages/index.tsx
- pages/zen-bull-netting.tsx
- store/calmBullStore.ts
> Add bull netting

- README.md
- pages/_app.tsx
- pages/swaps.tsx
- server/utils/ether.ts
> Update provider to alchemy

- container/CrabV2/Auction/AuctionInfo.tsx
Text to explain about Tuesday auction.
Fixes ENG-1921
> Added text for tuesday auction

- container/CrabV2/Auction/Admin/AdminBidView.tsx
- types/index.ts
- utils/auction.ts
> fix: check for nonce used
